@startuml sequence
participant Student1 as st1
participant System as sys
participant EnergyCompany as ec
participant XRPLedger as xl
database TxDatabase as db2

st1 --> sys : request more electricity
sys --> xl : request to send token to Student 
xl --> xl : add XRP token(Student1)\nremove XRP token(System)
sys --> db2 : report transaction\n(price & amount) 
@enduml