@startuml sequence
participant System   as sys
database UsageDatabase as db1
participant XRPLedger as xl

sys --> db1 : request student usage data
db1 --> sys : show student usage data
sys --> xl : request transaction\n(debit student's token)
xl --> xl : add XRP token(System)\nremove XRP token(Student1)
@enduml