@startuml sequence
participant System   as sys
database UsageDatabase as db
participant XRPLedger as xl
participant Student1 as st1

sys --> db : request student usage data
db --> sys : show student usage data
sys --> xl : request to debit student's token
xl --> st1 : remove XRP token
xl --> sys : add XRP token
@enduml