@startuml sequence
participant Student1 as st1
participant System as sys
participant EnergyCompany as ec
participant XRPLedger as xl

st1 --> sys : request more electricity
sys --> ec : buy electricity
ec --> sys : provide electricity
sys --> xl : request to send token to Student 
xl --> st1 : add XRP token(company)
xl --> sys : remove XRP token(company)

@enduml