@startuml sequence
participant Student1          as st1
participant System            as sys
participant XRPLedger         as xl

st1 --> sys : desired electoricity\n(solar or energy company )
sys --> xl : request transaction\n(System to Student1)
xl --> xl : add XRP token(Student1)\nremove XRP token(System)
@enduml
