@startuml sequence
participant StudentAccountant as sa
database UsageDatabase as db1
database TxDatabase as db2
participant UnivAccountant as ua

sa --> db1 : request usage data in network
sa <-- db1 : send usage data in network
sa --> db2 : request market data
sa <-- db2 : send market data
sa --> ua : report monthly data in network
@enduml