@startuml sequence

participant System      as sys #00FF00
participant Alice    as st1
participant Bob    as st2
participant XRPLedger   as xl #00FFFF
database  UsageDatabase as db1
database TxDatabase     as db2 #00FFFF

== Beginning of the Month ==
autonumber 1.1
sys --> db1 : request last year usage data
db1 --> sys : send last year usage data
sys --> st1 : send last year usage data \nand calculated this month usage
group Tx
sys --> xl : request transaction\n(System to Alice)
xl --> xl : add XRP token(Alice)\nremove XRP token(System)
sys --> db2 : report transaction\n(price & amount)
end

== Single Price Auction Market ==
autonumber inc A
st1 --> sys : send bid\n(price & amount)
st2 --> sys : send ask\n(price & amount)
sys --> sys : calculate winning bid
group Tx
sys --> xl : request transaction\n(Bob to Alice)
xl --> xl : add XRP token(Alice)\nremove XRP token(Bob)
sys --> db2 : report transaction\n(price & amount)
end

== Daily Settlement ==
autonumber inc A
sys --> db1 : request student usage data
db1 --> sys : show student usage data
group Tx
sys --> xl : request transaction\n(debit student's token)
xl --> xl : add XRP token(System)\nremove XRP token(Alice)
end

== End of the Month ==
autonumber inc A
sys --> xl : inquiry student's token balance
xl --> sys : send data(student's token balance)
sys --> st1 : buy Alice's long token
sys --> st2 : sell Bob's short token
group Tx
sys --> xl : request transaction(Stundent1 to System)
xl --> xl : add XRP token(System)\nremove XRP token(Alice)
sys --> xl : request transaction(System to Bob)
xl --> xl : add XRP token(Bob)\nremove XRP token(System)
sys --> db2 : report transaction\n(price & amount)
end
@enduml
